// <auto-generated />
namespace CarInsurance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class QuoteNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuoteNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202605102007540_QuoteNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
